#!/bin/bash

# Uncomment the following two lines for normal desktop:
# unset SESSION_MANAGER
# exec /etc/X11/xinit/xinitrc

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources

xmodmap -e "keycode 0x73 = Super_L" # left Command
xmodmap -e "keycode 0x74 = Super_R" # right Command

#xmodmap -e "keycode 0x16 = Delete" # BackSpace
#xmodmap -e "keycode 0x6B = BackSpace" # Delete

xsetroot -solid grey
xterm &

cd /var/lib/symbolics
xterm -e ./genera &
ratpoison &
