#!/bin/bash

wd=/var/lib/symbolics
cmd="./genera -geometry 1150x900 2>&1 > genera.log"
pidfile="$wd/genera.pid"
exec="$wd/genera"
HOME=/root DISPLAY=:1 sudo /sbin/start-stop-daemon --start --background --quiet --oknodo \
			--chdir "$wd" --exec "$exec" --startas /bin/bash -- -c "$cmd"

