#!/bin/bash

# Uncomment the following two lines for normal desktop:
# unset SESSION_MANAGER
# exec /etc/X11/xinit/xinitrc

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources

xsetroot -solid grey

xmodmap -e "keycode 0x73 = Super_L" # left Command
xmodmap -e "keycode 0x74 = Super_R" # right Command

#xmodmap -e "keycode 0x16 = Delete" # BackSpace
#xmodmap -e "keycode 0x6B = BackSpace" # Delete

ratpoison &
sleep 2

xterm &

cd /var/lib/symbolics
/var/lib/symbolics/run-genera &

#
# This is a terrible hack. For reasons as yet unknown, the
# first time Genera is launched after starting vncserver,
# it comes up into a partially cold-booted state that is
# unusable. At least for me, this happens 100% of the time.
# Restarting it, likewise, always gets it running.
#

sleep 5

exec /usr/local/bin/restart-genera &
